name: Run Tests

on:
  workflow_call:
    inputs:
      install_string:
        required: True
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      ##############################################
      # Skip caching if using a local runner.
      - uses: actions/setup-python@v4
        if: ${{ !env.ACT }}
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: "pyproject.toml"
      - uses: actions/setup-python@v4
        if: ${{ env.ACT }}
        with:
          python-version: '3.10'
      ##############################################

      - name: Install torch
        run: pip install torch==2.5.1 torchvision==0.20.1

      - name: Install torch_scatter
        run: pip install torch_scatter -f https://data.pyg.org/whl/torch-2.5.0+cpu.html

      - name: Install package
        run: pip install "${{ inputs.install_string }}"

      - name: Install spconv.
        run: pip install spconv

      - name: Code Quality
        run: python -m black src/ tests/ --check

      - name: MyPy Typechecking
        run: python -m mypy src/ tests/

      # Run tests.
      - name: Test with pytest
        run: python -m pytest
